name: nix-store-explorer

on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Add pytest
        run: poetry add pytest
      - name: Add bandit
        run: poetry add bandit
      - name: Add fastapi
        run: poetry add fastapi
      - name: Add openapi
        run: poetry add openapi
      - name: Add starlette
        run: poetry add starlette
      - name: Add bcrypt
        run: poetry add bcrypt
      - name: Add uvicorn
        run: poetry add uvicorn
      - name: Add pathlib
        run: poetry add pathlib
      - name: Add flake8
        run: poetry add flake8
      - name: Run bandit
        run: poetry run bandit app\api.py, bandit app\db.py, bandit app\main.py, bandit app\nix.py